FROM ubuntu

MAINTAINER leo090990@hotmail.com

ENV EXIFTOOL_VERSION=10.20

COPY /build/bin/skycatch_test /bin/

RUN apt-get update && apt-get -y install build-essential
RUN apt-get -y install wget
RUN cd /tmp \
	&& wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz \
	&& tar -zxvf Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz \
	&& cd Image-ExifTool-${EXIFTOOL_VERSION} \
	&& perl Makefile.PL \
	&& make test \
	&& make install \
	&& cd .. \
	&& rm -rf Image-ExifTool-${EXIFTOOL_VERSION}